# Nixpacks configuration for Analysis Service
[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 pydantic==2.5.3 pydantic-settings==2.1.0 python-dotenv==1.0.0"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"