# Railway Configuration - Analysis Service
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[environment]
PYTHONUNBUFFERED = "1"
SERVICE_NAME = "analysis"