[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "transcription-api"
port = 8000

[[services.volumes]]
mount = "/data"
name = "transcription-storage"

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"