# Stage Classification Checklist
# 수업 단계 분류: 도입(Introduction) / 전개(Development) / 정리(Closing)
#
# 3회 실행 후 다수결 투표로 최종 결정
# GPT-4o-mini, temperature=0 for consistency

stages:
  introduction:
    name: "도입"
    english: "Introduction"
    description: "수업의 시작 단계로 학습 목표를 제시하고 동기를 유발하는 단계"

    checklist:
      - id: "intro_01"
        question: "이 발화에서 오늘의 학습 목표나 주제를 명시적으로 제시하고 있습니까?"
        examples:
          positive:
            - "오늘은 이차방정식의 근의 공식에 대해 배워보겠습니다"
            - "자, 이번 시간에는 광합성 과정을 공부할 거예요"
            - "오늘의 학습 목표는 민주주의의 특징을 이해하는 것입니다"
          negative:
            - "그러면 이 문제를 풀어볼까요?" # 전개 단계
            - "오늘 배운 내용을 정리해봅시다" # 정리 단계

      - id: "intro_02"
        question: "이 발화에서 이전 학습 내용을 상기시키거나 복습하고 있습니까?"
        examples:
          positive:
            - "지난 시간에 우리가 일차방정식을 배웠죠?"
            - "저번에 배운 세포 구조 기억나나요?"
            - "전 시간에 배운 역사적 배경을 떠올려봅시다"
          negative:
            - "이 공식을 적용해서 풀어보세요" # 전개
            - "오늘 배운 걸 복습해봅시다" # 정리

      - id: "intro_03"
        question: "이 발화에서 학생들의 흥미를 유발하거나 동기를 부여하고 있습니까?"
        examples:
          positive:
            - "이 원리를 알면 스마트폰이 어떻게 작동하는지 이해할 수 있어요"
            - "여러분, 이거 알면 수능에서 정말 유용해요"
            - "재미있는 실험을 하나 보여줄게요"
          negative:
            - "그러면 공식에 대입해서 계산하세요" # 전개

      - id: "intro_04"
        question: "이 발화에서 수업의 전체 흐름이나 활동 순서를 안내하고 있습니까?"
        examples:
          positive:
            - "먼저 개념을 설명하고, 그 다음 문제를 풀어볼게요"
            - "오늘은 실험하고, 결과를 정리하고, 발표하는 순서로 진행합니다"
            - "이론 설명 15분, 모둠 활동 20분, 발표 10분 순서예요"
          negative:
            - "자, 이제 다음 문제로 넘어갑시다" # 전개

      - id: "intro_05"
        question: "이 발화에서 출석을 확인하거나 수업 시작을 알리고 있습니까?"
        examples:
          positive:
            - "자, 모두 자리에 앉았나요? 시작하겠습니다"
            - "출석 부르겠습니다. 김철수?"
            - "다들 준비됐죠? 수업 시작할게요"
          negative:
            - "문제 다 풀었나요?" # 전개

  development:
    name: "전개"
    english: "Development"
    description: "핵심 내용을 설명하고 학습 활동을 진행하는 단계"

    checklist:
      - id: "dev_01"
        question: "이 발화에서 새로운 개념이나 지식을 설명하고 있습니까?"
        examples:
          positive:
            - "이차방정식의 판별식은 b²-4ac입니다"
            - "광합성은 빛 에너지를 화학 에너지로 전환하는 과정이에요"
            - "민주주의의 핵심은 국민주권 원리입니다"
          negative:
            - "오늘은 광합성을 배울 거예요" # 도입
            - "오늘 배운 개념 정리해볼까요?" # 정리

      - id: "dev_02"
        question: "이 발화에서 예시나 사례를 들어 설명하고 있습니까?"
        examples:
          positive:
            - "예를 들어, x²-5x+6=0이라는 방정식이 있다면"
            - "실생활에서 광합성의 예로는 나뭇잎의 녹색이 있어요"
            - "우리나라의 경우를 보면"
          negative:
            - "예시를 들어볼까요?" # 질문만 하는 것은 제외

      - id: "dev_03"
        question: "이 발화에서 문제 풀이나 실습 활동을 지도하고 있습니까?"
        examples:
          positive:
            - "이 공식에 숫자를 대입해서 계산해보세요"
            - "각자 실험 기구를 준비하고 진행해보세요"
            - "모둠별로 토론해서 답을 찾아보세요"
          negative:
            - "다 풀었으면 정리해볼까요?" # 정리

      - id: "dev_04"
        question: "이 발화에서 학생의 답변이나 질문에 대해 피드백하고 있습니까?"
        examples:
          positive:
            - "맞아요, 정확하게 이해했네요"
            - "아쉽지만 틀렸어요. 다시 생각해보세요"
            - "좋은 질문이에요. 그 부분을 다시 설명하면"
          negative:
            - "질문 있나요?" # 단순 질문 요청

      - id: "dev_05"
        question: "이 발화에서 심화 내용이나 응용 방법을 설명하고 있습니까?"
        examples:
          positive:
            - "이 원리를 좀 더 확장하면"
            - "고급 과정에서는 이렇게 응용할 수 있어요"
            - "실제 현장에서는 이렇게 활용됩니다"
          negative:
            - "오늘은 기본 개념만 배울게요" # 도입

      - id: "dev_06"
        question: "이 발화에서 학생들의 이해도를 확인하는 질문을 하고 있습니까?"
        examples:
          positive:
            - "이해됐나요? 모르는 부분 있어요?"
            - "누가 이 개념을 다시 설명해볼 수 있나요?"
            - "어느 부분이 어려웠어요?"
          negative:
            - "오늘 배운 걸 정리해봅시다" # 정리

  closing:
    name: "정리"
    english: "Closing"
    description: "학습 내용을 요약하고 다음 차시를 예고하는 단계"

    checklist:
      - id: "close_01"
        question: "이 발화에서 오늘 배운 핵심 내용을 요약하거나 정리하고 있습니까?"
        examples:
          positive:
            - "오늘 배운 중요한 내용을 정리하면"
            - "핵심은 근의 공식 b²-4ac였습니다"
            - "광합성의 3단계를 다시 한번 복습하면"
          negative:
            - "이제 새로운 개념을 배워봅시다" # 전개
            - "오늘은 광합성을 배울 거예요" # 도입

      - id: "close_02"
        question: "이 발화에서 과제나 숙제를 안내하고 있습니까?"
        examples:
          positive:
            - "오늘 숙제는 교과서 50페이지 문제 1번부터 5번까지예요"
            - "집에서 복습하고 다음 시간에 퀴즈 볼게요"
            - "워크북 풀어오는 것 잊지 마세요"
          negative:
            - "이 문제를 지금 풀어보세요" # 전개

      - id: "close_03"
        question: "이 발화에서 다음 차시 내용을 예고하고 있습니까?"
        examples:
          positive:
            - "다음 시간에는 근의 공식을 응용한 문제를 풀어볼게요"
            - "다음 주에는 호흡 작용에 대해 배울 겁니다"
            - "다음 시간에 이어서 할 거예요"
          negative:
            - "오늘은 이차방정식을 배웁니다" # 도입

      - id: "close_04"
        question: "이 발화에서 학생들의 학습 성취를 칭찬하거나 격려하고 있습니까?"
        examples:
          positive:
            - "오늘 모두 열심히 했어요, 수고했습니다"
            - "다들 잘 이해한 것 같네요, 훌륭해요"
            - "어려운 내용이었는데 잘 따라와줘서 고마워요"
          negative:
            - "잘하고 있어요, 계속 풀어보세요" # 전개 중 격려

      - id: "close_05"
        question: "이 발화에서 수업을 마무리하거나 종료를 알리고 있습니까?"
        examples:
          positive:
            - "오늘 수업은 여기까지입니다"
            - "시간이 됐네요, 마치겠습니다"
            - "다들 수고하셨어요, 다음 시간에 봐요"
          negative:
            - "시작하겠습니다" # 도입

      - id: "close_06"
        question: "이 발화에서 질의응답 시간을 가지며 최종 확인을 하고 있습니까?"
        examples:
          positive:
            - "마지막으로 질문 있나요?"
            - "헷갈리는 부분 있으면 지금 물어보세요"
            - "끝나기 전에 궁금한 거 없어요?"
          negative:
            - "이 부분 이해 안 되는 사람?" # 전개 중 확인

# 분류 규칙
classification_rules:
  decision_method: "majority_voting"
  num_runs: 3
  threshold:
    introduction: 3  # 5개 체크리스트 중 3개 이상 Yes
    development: 4   # 6개 체크리스트 중 4개 이상 Yes
    closing: 3       # 6개 체크리스트 중 3개 이상 Yes

  tie_breaking:
    # 여러 단계가 동시에 threshold를 넘는 경우
    priority: ["development", "introduction", "closing"]
    # 전개 > 도입 > 정리 순으로 우선순위

  fallback:
    # threshold를 넘는 단계가 없는 경우
    default: "development"
    reason: "대부분의 수업 시간은 전개 단계에 해당"

# 프롬프트 템플릿
prompt_template: |
  다음은 교사의 수업 발화입니다. 이 발화가 수업의 어느 단계에 해당하는지 분류하기 위한 체크리스트입니다.

  각 질문에 대해 "Yes" 또는 "No"로만 답변하세요.

  **발화 내용:**
  "{utterance}"

  **발화 맥락:**
  - 발화 시간: {timestamp}
  - 이전 발화: "{previous_utterance}"
  - 다음 발화: "{next_utterance}"

  **체크리스트 ({stage_name}):**
  {checklist_items}

  각 질문에 대한 답변을 다음 형식으로 제공하세요:
  {{
    "intro_01": "Yes/No",
    "intro_02": "Yes/No",
    ...
  }}

  추가 설명 없이 JSON 형식으로만 답변하세요.
