# Streamlit Configuration for AIBOA Frontend

[theme]
# Primary color for interactive elements
primaryColor = "#1E88E5"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text
font = "sans serif"

[server]
# Max size for file uploads (in MB)
maxUploadSize = 200

# Max size for message payloads (in MB)
maxMessageSize = 200

# Enables CORS protection
enableCORS = false

# Enables XSRF protection
enableXsrfProtection = true

# Enables support for websocket compression
enableWebsocketCompression = true

# Port to use for the server
port = 8501

[browser]
# Internet address where users should point their browsers
serverAddress = "0.0.0.0"

# Whether to send usage statistics to Streamlit
gatherUsageStats = false

# Port where users should point their browsers
serverPort = 8501

[runner]
# Allows you to type a variable or string by itself to write it to the app
magicEnabled = true

# Install a Python tracer to allow you to stop/resume execution
installTracer = false

# Sets the MPLBACKEND environment variable
fixMatplotlib = true

[client]
# Whether to enable st.cache
caching = true

# If false, makes your Streamlit app not draw to a Streamlit app
displayEnabled = true

# Controls whether uncaught app exceptions are displayed in the browser
showErrorDetails = true

# Change the visibility of toolbar
toolbarMode = "minimal"