# Streamlit Configuration for AIBOA Frontend

[theme]
# Primary color for interactive elements
primaryColor = "#1E88E5"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text
font = "sans serif"

[server]
# Max size for file uploads (in MB)
maxUploadSize = 200

# Max size for message payloads (in MB)
maxMessageSize = 200

# Enables CORS protection (must be true when enableXsrfProtection is true)
enableCORS = true

# Enables XSRF protection
enableXsrfProtection = true

# Enables support for websocket compression
enableWebsocketCompression = true

# Run in headless mode for server deployment
headless = true

[browser]
# Whether to send usage statistics to Streamlit
gatherUsageStats = false

[runner]
# Allows you to type a variable or string by itself to write it to the app
magicEnabled = true

# Perform garbage collection after each script run
postScriptGC = true

[client]
# Controls whether uncaught app exceptions are displayed in the browser
showErrorDetails = true

# Change the visibility of toolbar
toolbarMode = "minimal"

[logger]
# Log level
level = "info"