#!/bin/bash

echo "=== Railway Deployment Verification ==="
echo ""
echo "Please check the Railway dashboard for the following:"
echo ""
echo "For teaching_analize service:"
echo "1. Go to Settings tab"
echo "2. Check 'Root Directory' - should be: /services/transcription (or leave empty for root)"
echo "3. Check 'Build Command' - should be empty or: docker build ."
echo "4. Check 'Start Command' - should be empty (uses Dockerfile CMD)"
echo "5. Check Environment Variables:"
echo "   - PORT should be set (Railway provides this)"
echo "   - OPENAI_API_KEY should be set"
echo ""
echo "For amused-friendship service:"
echo "1. Go to Settings tab"
echo "2. Check 'Root Directory' - should be: /services/analysis (or leave empty for root)"
echo "3. Check 'Build Command' - should be empty or: docker build ."
echo "4. Check 'Start Command' - should be empty (uses Dockerfile CMD)"
echo "5. Check Environment Variables:"
echo "   - PORT should be set (Railway provides this)"
echo "   - OPENAI_API_KEY should be set"
echo "   - UPSTAGE_API_KEY should be set"
echo ""
echo "Common issues:"
echo "- If Root Directory has leading slash, remove it (use 'services/transcription' not '/services/transcription')"
echo "- If using Nixpacks, switch to Docker by ensuring Dockerfile exists"
echo "- Check the deployment logs in Railway dashboard for specific errors"
echo ""
echo "Current deployment attempts:"
railway logs --service teaching_analize 2>/dev/null | head -5
railway logs --service amused-friendship 2>/dev/null | head -5